version: "3"
services:
  bot:
    build: .
    environment:
      - PK_TOKEN
      - "PK_DATABASE_URI=Host=db;Username=postgres;Password=postgres;Database=postgres"
    links:
      - db
  db:
    image: postgres:alpine