version: "3"
services:
  bot:
    build: .
    entrypoint: ["dotnet", "run", "--project", "PluralKit.Bot"]
    environment:
      - "PluralKit:Database=Host=db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
      - "PluralKit:InfluxUrl=http://influx:8086"
      - "PluralKit:InfluxDb=pluralkit"
      - "PluralKit:LogDir=/var/log/pluralkit"
    volumes:
      - "./pluralkit.conf:/app/pluralkit.conf:ro"
      - "/var/log/pluralkit:/var/log/pluralkit"
    links:
      - db
      - influx
    restart: always
  web:
    build: .
    entrypoint: ["dotnet", "run", "--project", "PluralKit.Web"]
    environment:
      - "PluralKit:Database=Host=db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
    links: 
      - db
    ports:
      - 2837:5000
    restart: always
  api:
    build: .
    entrypoint: ["dotnet", "run", "--project", "PluralKit.API"]
    environment:
      - "PluralKit:Database=Host=db;Username=postgres;Password=postgres;Database=postgres;Maximum Pool Size=1000"
    links:
      - db
    ports:
      - 2838:5000
    restart: always
  db:
    image: postgres:alpine
    volumes:
      - "db_data:/var/lib/postgresql/data"
    restart: always
    command: ["postgres", "-c", "max-connections=1000"]
  influx:
    image: influxdb:alpine
    volumes:
      - "influx_data:/var/lib/influxdb"
    ports:
      - 2839:8086
    restart: always
    
volumes:
  db_data:
  influx_data:
