version: '3'
services:
  bot:
    build: bot
    depends_on:
    - db
    environment:
    - TOKEN
  db:
    image: postgres:alpine
    volumes:
    - db_data:/var/lib/postgres
    restart: always
volumes:
  db_data: