version: '3'
services:
  bot:
    build: src/
    entrypoint:
    - python
    - bot_main.py
    depends_on:
    - db
    environment:
    - CLIENT_ID
    - TOKEN
    - LOG_CHANNEL
    - TUPPERWARE_ID
    - "DATABASE_USER=postgres"
    - "DATABASE_PASS=postgres"
    - "DATABASE_NAME=postgres"
    - "DATABASE_HOST=db"
    - "DATABASE_PORT=5432"
    restart: always
  api:
    build: src/
    entrypoint:
    - python
    - api_main.py
    depends_on:
    - db
    restart: always
    ports:
    - "2939:8080"
    environment:
    - "DATABASE_USER=postgres"
    - "DATABASE_PASS=postgres"
    - "DATABASE_NAME=postgres"
    - "DATABASE_HOST=db"
    - "DATABASE_PORT=5432"
  db:
    image: postgres:alpine
    volumes:
    - "db_data:/var/lib/postgresql/data"
    restart: always

volumes:
  db_data: