version: '3'
services:
  bot:
    build: bot
    depends_on:
    - db
    - influx
    environment:
    - CLIENT_ID
    - TOKEN
    restart: always
  db:
    image: postgres:alpine
    volumes:
    - "db_data:/var/lib/postgresql/data"
    restart: always
  influx:
    image: influxdb:alpine
    volumes:
    - "influx_data:/var/lib/influxdb:Z"
    restart: always
  grafana:
    build: grafana
    depends_on:
    - influx
    ports:
    - "2938:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USERNAME}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    restart: always

volumes:
  db_data:
  influx_data: